Single cmd entrypoint (#59)
## 📝 Summary

Update to have a single entrypoint, instead of four distinct binaries.

Works overall, as you can see in this release:
https://github.com/flashbots/mempool-dumpster/releases/tag/v0.9.1-rc6

---

The CI is still having some failure on retrying uploads, not sure why:
https://github.com/flashbots/mempool-dumpster/actions/runs/15346111658/job/43182577556?pr=59

```
      • upload failed                                request-id=AC40:3A90E:183A995:1CB0066:68399BA5 error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_riscv64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=mempool-dumpster_0.9.1-rc6_linux_riscv64.tar.gz release-id=222057616
      • failed to upload artifact, will retry        try=2 artifact=mempool-dumpster_0.9.1-rc6_linux_riscv64.tar.gz error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_riscv64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
      • upload failed                                request-id=AC40:3A90E:183A9E9:1CB00BE:68399BA5 error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_darwin_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=mempool-dumpster_0.9.1-rc6_darwin_arm64.tar.gz release-id=222057616
      • failed to upload artifact, will retry        try=2 artifact=mempool-dumpster_0.9.1-rc6_darwin_arm64.tar.gz error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_darwin_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
      • upload failed                                request-id=AC40:3A90E:183A9E9:1CB00BC:68399BA5 error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=mempool-dumpster_0.9.1-rc6_linux_arm64.tar.gz release-id=222057616
      • failed to upload artifact, will retry        try=2 artifact=mempool-dumpster_0.9.1-rc6_linux_arm64.tar.gz error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_arm64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
      • upload failed                                request-id=AC40:3A90E:183A9E9:1CB00BB:68399BA5 error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_darwin_amd64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=mempool-dumpster_0.9.1-rc6_darwin_amd64.tar.gz release-id=222057616
      • failed to upload artifact, will retry        try=2 artifact=mempool-dumpster_0.9.1-rc6_darwin_amd64.tar.gz error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_darwin_amd64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
      • upload failed                                request-id=AC40:3A90E:183A9E9:1CB00BD:68399BA5 error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_amd64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}] name=mempool-dumpster_0.9.1-rc6_linux_amd64.tar.gz release-id=222057616
      • failed to upload artifact, will retry        try=2 artifact=mempool-dumpster_0.9.1-rc6_linux_amd64.tar.gz error=POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_linux_amd64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
  ⨯ release failed after 25s                 error=scm releases: failed to publish artifacts: failed to upload mempool-dumpster_0.9.1-rc6_checksums.txt after 2 tries: POST https://uploads.github.com/repos/flashbots/mempool-dumpster/releases/222057616/assets?name=mempool-dumpster_0.9.1-rc6_checksums.txt: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.9.0/x64/goreleaser' failed with exit code 1
```